### ISSUE TITLE
Error message "could not find repository from '.'; class=Repository (6); code=NotFound (-3)"

### ISSUE THREAD

**Issue by musaa01** [BrettMayson/HEMTT#482]
I'm running into an issue making a PBO files from the gruppe-adler mod GRAD_CIVS source file from https://github.com/gruppe-adler/grad_civs/releases/tag/6.7.1.  I was able to download and unpack the folder to my desktop (C:\Users\username\OneDrive\Desktop\grad_civs-6.7.1\grad_civs-6.7.1) and download and unpack the 64bit hemtt.exe to by documents folder (C:\Users\username\OneDrive\Documents\HEMTT).  I also copied the hemtt.exe to the C:\Users\musaa\OneDrive\Desktop\grad_civs-6.7.1\grad_civs-6.7.1 folder where the hemtt toml file is located.  When I open the command prompt, I change directory to C:\Users\username\OneDrive\Desktop\grad_civs-6.7.1\grad_civs-6.7.1 and typed "hemtt.exe build".  It runs for several seconds, completes checks (16/16), completes prebuild (16/16), but on build, I get the following error: "could not find repository from '.'; class=Repository (6); code=NotFound (-3)".  I also tried running hemtt by typing "C:\Users\username\OneDrive\Documents\HEMTT\hemtt.exe build", but that too gives me the same error.  The TOML file appears to have all the data needed as per the HEMTT book: 
name = "Gruppe Adler Civilians"
prefix = "grad_civs"
author = "Gruppe Adler"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

I'm at a loss as to what the "could not find repository from '.';" refers to.  Any help at to what this reference is would be much appreciated as I'm testing to see if I can get Grad_Civs to spawn vehicles in the center of the road instead of on the curb to avoid vehicles exploding if they clip nearby buildings.

**Comment by Seb105** [comment]
Had the same issue. Was apparently due to having the mod folder as aa github repo. Try adding this to your `project.toml`

```toml
[version]
git_hash = 0
```

**Comment by Eathox** [comment]
More specifically HEMTT by default uses the first 8 characters of the most recent git commit as an additional version field, see the [HEMTT book git hash](https://brettmayson.github.io/HEMTT/configuration-version.html#git-hash) section. The way it does this is by accessing the `.git` folder at the root of your project, this folder is required for any git interactions so if you can do any git commands that means its present. 

A source code zip does not include the git information so also doesn't include this `.git` folder, therefor HEMTT cant access it and you get an error. You can either clone the repo using git (instead of downloading the source code zip) and if you specifically need version `6.7.1` use the tag: [6.7.1](https://github.com/gruppe-adler/grad_civs/tree/6.7.1) or, as @Seb105 suggested you can disable this setting by adding the following to your `.hemtt/project.toml`
```toml
[version]
git_hash = 0
```
