### ISSUE TITLE
Value command too slow

### ISSUE THREAD

**Issue by Timi007** [BrettMayson/HEMTT#650]
**Versions:**
HEMTT: `1.11.1`

**Description:**

The `hemtt value` command takes too long (>1 second) to process. 

I executed following code in Powershell three times and taken the last value as the result. I've done this to ensure HEMTT doesn't start cold. However, I saw that it doesn't matter either way. 
```ps1
Measure-Command { hemtt value project.name | Out-Default }
```

Measured on an `i5-8600K@4.80GHz`.

**Results:**
- ACE3: 9.6 sec
- CBA3: 1.0 sec
- ACRE2: 8.3 sec
- [Metis Marker](https://github.com/Metis-Team/mts_marker): 11.1 sec
- [Metis Enhanced](https://github.com/Metis-Team/mts_enhanced): 4.4 sec

My guess is that the VFS takes too long to build. Metis Marker only has one PBO but many files which need to be added. Hence the long setup time of the VFS.

Does the `value` command need to rely on the VFS?

**Comment by BrettMayson** [comment]
After cloning Metis Marker, the value command runs consistently in about 100ms, possibly the VFS, but that is quite a difference in speeds to attribute it to that right away

Do you happen to be running it on a hard drive or SSD?

**Comment by BrettMayson** [comment]
Fixed in 8159b471537fd7022e601d6891aeb842da5b5d8d

Windows was taking its sweet time opening file handles for some reason, up to 0.73 seconds on my machine.

The VFS is "required", `hemtt value` could have it's own dedicated code to avoid using the VFS, but I don't really want to go that route. The slowest part of the code was been disabled during the `hemtt value` command.
