### ISSUE TITLE
Vritual File System Changes are not correctly passed to ASC/SqfC files

### ISSUE THREAD

**Issue by jokoho48** [BrettMayson/HEMTT#682]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.12.0`
- **Operating System:** Windows 11 23H2

**Description:**
In some cases, when modifying a macro file in the pre_build step in the Virtual File System, the change is not correctly represented in output sqfc files.

**Steps to reproduce:**

1. Clone `git clone -b HEMTT_REPRO_TEST_CASE https://github.com/TaktiCool/CLib.git`
2. Run 'hemtt release'
3. unpack release zip and PBO
4. check hemtt_test_case.sqfc in CLib/Core folder

**Expected behavior:**
function when compiled and called ingame via compileScript should log `"=================== IS DEV IS NOT ACTIVE!!!! ==================="`

**Additional context:**
when switching https://github.com/TaktiCool/CLib/blob/HEMTT_REPRO_TEST_CASE/.hemtt/hooks/pre_build/set_is_dev.rhai from HEMTT_VFS to HEMTT_RFS it works as expected.

**Comment by BrettMayson** [comment]
The issue here was the prefix being set to the same value as the mainprefix, and not the actual prefix used in $PBOPREFIX$.

HEMTT was still managing to find the correct file (on windows, #683), but a version unedited by the hook and the use of the VFS, the RFS is more direct in its path mapping and therefor worked as expected.

Perhaps a warning if there is an addon where the prefix and $PBOPREFIX$ don't match, although that is perfectly fine and needed in rare cases.
